Repository DO-SOPT-CDS-TEAM-WEB7/Client, pull requests merged in 2023-12, with the labels that each got.

#44 [Feat] GET API 이용해서 최저가 섹션 구현
  src/apis/getMainFlights.ts
  src/assets/image/Group 145.png
  src/assets/image/Group 146.png
  src/assets/image/Group 147.png
  src/assets/image/Group 148.png
  src/assets/image/Group 149.png
  src/assets/image/Group 150.png
  src/assets/image/img_card_l_2_airline.png
  src/assets/image/img_card_l_3_airline.png
  src/assets/image/img_card_l_4_airline.png
  src/assets/image/img_card_l_5_airline.png
  src/assets/image/img_card_l_6_airline.png
  src/assets/image/index.ts
  src/components/main/LowestFlightItem.tsx
  src/components/main/LowestFlights.tsx
  src/data/LowestFlightItemData.ts
  src/pages/Main.tsx
  src/types/Main.ts
Labels: ✨ Feat, 메인

#47 [Feat] 항공권 리스트 비행기 티켓 API 연결
  src/apis/getTicketList.ts
  src/assets/image/img_airbusan.png
  src/assets/image/img_ana.png
  src/assets/image/img_jejuair.png
  src/assets/image/img_peach.png
  src/assets/image/index.ts
  src/components/common/Carousel.tsx
  src/components/common/SearchBar.tsx
  src/components/ticketList/HotelCarousel.tsx
  src/components/ticketList/Nav.tsx
  src/components/ticketList/Ticket.tsx
  src/components/ticketList/TicketItem.tsx
  src/data/TicketItemData.ts
  src/pages/TicketList.tsx
  src/types/ticketList.ts
Labels: ✨ Feat, 항공권 리스트

#49 [Feat] 항공권 정보 컴포넌트 구현
  src/apis/getApiTest.ts
  src/apis/getTicketReservation.ts
  src/assets/icon/ic_arrowdown_blue.svg
  src/assets/icon/ic_arrowup_blue.svg
  src/assets/icon/index.ts
  src/assets/icon/movingArrow.svg
  src/assets/icon/verticalLine.svg
  src/components/priceCompare/AirlineTicketList.tsx
  src/components/priceCompare/Banner.tsx
  src/components/priceCompare/Header.tsx
  src/components/priceCompare/TicketInfo.tsx
  src/components/priceCompare/TicketInfoList.tsx
  src/pages/ApiTest.tsx
  src/pages/PriceCompare.tsx
  src/types/apiTest.ts
  src/types/ticketReservationInfo.ts
Labels: ✨ Feat, 가격비교

#51 [Feat] 항공권 리스트 티켓 필터링
  src/apis/getMinPriceList.ts
  src/components/ticketList/DropDown.tsx
  src/components/ticketList/DropDown/ButtonContainer.tsx
  src/components/ticketList/DropDown/DurationDropDown.tsx
  src/components/ticketList/DropDown/FlightDropDown.tsx
  src/components/ticketList/DropDown/PathDropDown.tsx
  src/components/ticketList/DropDown/TimeDropDown.tsx
  src/components/ticketList/HotelCarousel.tsx
  src/components/ticketList/Ticket.tsx
  src/pages/TicketList.tsx
  src/types/ticketList.ts
Labels: ✨ Feat, 항공권 리스트

#56 [Design] 메인 뷰 레이아웃
  package.json
  src/assets/image/index.ts
  src/assets/image/main_banner.png
  src/components/common/SearchBar.tsx
  src/components/main/Calendar.tsx
  src/components/main/CalendarItem.tsx
  src/components/main/Header.tsx
  src/components/main/Insight.tsx
  src/components/main/Nav.tsx
  src/components/main/QnA.tsx
  src/pages/Main.tsx
Labels: 💄 Design, 메인

#58 [Design] footer 디자인 수정
  src/components/common/Footer.tsx
  src/pages/Main.tsx
Labels: 💄 Design, 공통 컴포넌트

#59 [Design] 항공권 리스트 전체 배경색 추가
  src/components/common/SearchBar.tsx
  src/components/ticketList/DropDown.tsx
  src/components/ticketList/DropDown/DurationDropDown.tsx
  src/components/ticketList/DropDown/FlightDropDown.tsx
  src/components/ticketList/DropDown/PathDropDown.tsx
  src/components/ticketList/DropDown/RecommendDropDown.tsx
  src/components/ticketList/DropDown/TimeDropDown.tsx
  src/components/ticketList/DropDown/styles/DropDown.style.ts
  src/components/ticketList/Ticket.tsx
  src/components/ticketList/TicketItem.tsx
  src/pages/Main.tsx
  src/pages/TicketList.tsx
  src/types/ticketList.ts
Labels: 💄 Design, 항공권 리스트

#63 [Feat] 날짜 넣어놓기
  src/components/main/Calendar.tsx
Labels: ✨ Feat, 항공권 리스트
