Repository DO-SOPT-CDS-TEAM-WEB7/Client, pull requests merged in 2023-11, with the labels that each got.

#8 [Init] 반응형 설정
  src/styles/globalStyle.ts
Labels: 💡 Init

#11 [Init] 글로벌 스타일 수정
  index.html
  src/App.tsx
  src/components/main/MainTest.tsx
  src/styles/globalStyle.ts
Labels: 💡 Init

#17 [init] 컬러코드 수정 및 추가, 그림자 effects 추가
  src/styles/theme.ts
Labels: 💡 Init

#18 [feat] 메인뷰 QnA 섹션 구현
  src/assets/icon/ic_arrow_down.svg
  src/assets/icon/ic_arrow_right_gray.svg
  src/assets/icon/ic_arrowdown.svg
  src/assets/icon/index.ts
  src/components/main/QnA.tsx
  src/pages/Main.tsx
Labels: ✨ Feat, 메인

#9 [Feat] 공통 캐러셀
  package.json
  src/assets/image/chevron.backward.png
  src/assets/image/chevron.forward.png
  src/assets/image/icn_heart.png
  src/assets/image/icn_star@2x.png
  src/assets/image/img_hotel_1@2x.png
  src/assets/image/img_hotel_2@2x.png
  src/assets/image/img_hotel_3@2x.png
  src/assets/image/img_hotel_4@2x.png
  src/assets/image/img_hotel_5.png
  src/assets/image/img_hotel_6.png
  src/assets/image/img_hotel_7.png
  src/assets/image/img_hotel_8.png
  src/assets/image/index.ts
  src/components/common/Carousel.tsx
  src/components/common/Router.tsx
  src/components/ticketList/HotelCarousel.tsx
  src/components/ticketList/HotelItem.tsx
  src/components/ticketList/TicketListTest.tsx
  src/data/HotelItemData.ts
  yarn.lock
Labels: ✨ Feat, 공통 컴포넌트

#22 [Feat] 가격비교 페이지 Header 구현
  src/assets/icon/chevronLeft.svg
  src/assets/icon/index.ts
  src/assets/icon/priceCompareLogo.svg
  src/assets/image/headbanner.png
  src/assets/image/index.ts
  src/components/common/Router.tsx
  src/components/main/MainTest.tsx
  src/components/priceCompare/Header.tsx
  src/components/priceCompare/PriceCompareTest.tsx
  src/pages/PriceCompare.tsx
Labels: ✨ Feat, 가격비교

#13 [Feat] 메인 뷰 헤더 구현
  src/assets/icon/airplane.svg
  src/assets/icon/car.svg
  src/assets/icon/globe.svg
  src/assets/icon/heart.svg
  src/assets/icon/hotel.svg
  src/assets/icon/index.ts
  src/assets/icon/logo.svg
  src/assets/icon/menu.svg
  src/assets/icon/profile.svg
  src/components/main/Header.tsx
  src/pages/Main.tsx
Labels: ✨ Feat, 메인

#20 [Feat] Footer 구현
  src/assets/icon/chevronDown.svg
  src/assets/icon/index.ts
  src/components/common/Footer.tsx
  src/components/priceCompare/TicketInfo.tsx
Labels: ✨ Feat, 공통 컴포넌트

#15 [Feat] 공통 nav바
  src/App.tsx
  src/assets/image/checkbox@2x.png
  src/assets/image/index.ts
  src/components/common/SearchBar.tsx
Labels: ✨ Feat, 공통 컴포넌트

#24 [Feat] 항공권 리스트 페이지 Nav바 구현
  src/assets/icon/index.ts
  src/assets/icon/ticket_logo.svg
  src/assets/image/icn_airplane@2x.png
  src/assets/image/icn_bed@2x.png
  src/assets/image/icn_car@2x.png
  src/assets/image/icn_search.png
  src/assets/image/index.ts
  src/components/ticketList/Nav.tsx
Labels: ✨ Feat, 항공권 리스트

#27 [Feat] 인사이트 컴포넌트 구현
  src/assets/image/Rectangle 34624743.png
  src/assets/image/image-1.png
  src/assets/image/image.png
  src/assets/image/index.ts
  src/components/common/Router.tsx
  src/components/main/Insight.tsx
  src/pages/Main.tsx
Labels: ✨ Feat, 메인

#39 [Feat] axios instance 세팅
  package.json
  src/apis/client.ts
  src/apis/getApiTest.ts
  src/apis/test.ts
  src/pages/ApiTest.tsx
  src/types/apiTest.ts
  yarn.lock
Labels: ✨ Feat, 공통 컴포넌트

#33 [Feat] 비행기 추천 컴포넌트 구현
  src/assets/image/img_card_s_1.png
  src/assets/image/img_card_s_10 (2).png
  src/assets/image/img_card_s_10.png
  src/assets/image/img_card_s_11 (2).png
  src/assets/image/img_card_s_11.png
  src/assets/image/img_card_s_12 (2).png
  src/assets/image/img_card_s_12.png
  src/assets/image/img_card_s_2.png
  src/assets/image/img_card_s_3.png
  src/assets/image/img_card_s_4.png
  src/assets/image/img_card_s_5.png
  src/assets/image/img_card_s_6.png
  src/assets/image/img_card_s_7.png
  src/assets/image/img_card_s_8.png
  src/assets/image/img_card_s_9 (2).png
  src/assets/image/img_card_s_9.png
  src/assets/image/index.ts
  src/components/common/Router.tsx
  src/components/main/FlightCarousel.tsx
  src/components/main/FlightItem.tsx
  src/components/main/RecommendFlight.tsx
  src/data/FlightItemData.ts
  src/pages/Main.tsx
Labels: ✨ Feat, 메인

#31 [Feat] 여행지 추천 컴포넌트 구현
  src/assets/image/img_card_m_1.png
  src/assets/image/img_card_m_10 (1).png
  src/assets/image/img_card_m_10.png
  src/assets/image/img_card_m_11 (1).png
  src/assets/image/img_card_m_11.png
  src/assets/image/img_card_m_12 (1).png
  src/assets/image/img_card_m_12.png
  src/assets/image/img_card_m_2.png
  src/assets/image/img_card_m_3.png
  src/assets/image/img_card_m_4.png
  src/assets/image/img_card_m_5.png
  src/assets/image/img_card_m_6.png
  src/assets/image/img_card_m_7.png
  src/assets/image/img_card_m_8.png
  src/assets/image/img_card_m_9 (1).png
  src/assets/image/img_card_m_9.png
  src/assets/image/index.ts
  src/components/main/DesCarousel.tsx
  src/components/main/DesItem.tsx
  src/components/main/QnA.tsx
  src/components/main/RecommendDestination.tsx
  src/data/DesItemData.ts
  src/pages/Main.tsx
Labels: ✨ Feat, 메인

#29 [Feat] 항공권 리스트 항공권 티켓
  src/assets/image/icn_arrow.png
  src/assets/image/icn_heart@2x.png
  src/assets/image/img_airseoul@2x.png
  src/assets/image/img_asiana@2x.png
  src/assets/image/img_jinair@2x.png
  src/assets/image/img_koreanair@2x.png
  src/assets/image/index.ts
  src/assets/image/leaf.fill@2x.png
  src/components/common/Router.tsx
  src/components/ticketList/Ticket.tsx
  src/components/ticketList/TicketItem.tsx
  src/pages/TicketList.tsx
Labels: ✨ Feat, 항공권 리스트

#37 [Feat] 항공권 리스트 nav바 상단, 하단 이미지
  src/assets/image/img_ad.png
  src/assets/image/index.ts
  src/components/common/SearchBar.tsx
  src/components/ticketList/AdvImg.tsx
  src/components/ticketList/BackgroundImg.tsx
  src/components/ticketList/HotelItem.tsx
  src/components/ticketList/Nav.tsx
  src/pages/TicketList.tsx
Labels: ✨ Feat, 항공권 리스트

#35 [Feat] 항공권 리스트 항공권 필터 드롭다운
  src/assets/image/arrow_up.png
  src/assets/image/check.png
  src/assets/image/icn_arrow_default@2x.png
  src/assets/image/index.ts
  src/assets/image/tabbox_depart_graph_default.png
  src/components/common/Router.tsx
  src/components/ticketList/DropDown.tsx
  src/components/ticketList/DropDown/ButtonContainer.tsx
  src/components/ticketList/DropDown/DurationDropDown.tsx
  src/components/ticketList/DropDown/FlightDropDown.tsx
  src/components/ticketList/DropDown/PathDropDown.tsx
  src/components/ticketList/DropDown/RecommendDropDown.tsx
  src/components/ticketList/DropDown/TimeDropDown.tsx
  src/components/ticketList/DropDown/styles/DropDown.style.ts
  src/components/ticketList/DropDown/styles/Graph.style.ts
  src/components/ticketList/DropDown/styles/InputCustom.style.ts
  src/hooks/useOpenDropDown.tsx
  src/pages/TicketList.tsx
Labels: ✨ Feat, 항공권 리스트

#41 [Feat] 최저가 항공편 컴포넌트
  src/assets/icon/ic_arrow_right_blue.svg
  src/assets/icon/index.ts
  src/assets/image/img_card_l_1_airline.png
  src/assets/image/index.ts
  src/components/common/Router.tsx
  src/components/main/LowestFlightItem.tsx
Labels: ✨ Feat, 메인
